# Generated by Django 5.1.2 on 2024-11-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0002_telegramuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'польватель телеграмма', 'verbose_name_plural': 'полmзователи телеграмма'},
        ),
    ]
