# Generated by Django 5.1.2 on 2024-11-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0003_alter_telegramuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id_user',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
